In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("..\data\processed\cleaned_data.csv")
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9496\1379660515.py:1: DtypeWarning: Columns (0: item_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("..\data\processed\cleaned_data.csv")

,year,month,supplier,item_code,item_description,item_type,retail_sales,retail_transfers,warehouse_sales
0,2026,6,20705 IMPORTS,180496,PANAS ASSYRTIKO 750ML,WINE,0.0,0.0,2.0
1,2026,6,20705 IMPORTS,574386,PARDEVALLES ALBARIN BLANCO - 750ML,WINE,0.0,0.0,1.0
2,2026,6,20705 IMPORTS,171162,PROSECCO 84 - 750ML,WINE,0.0,0.0,4.0
3,2026,6,20705 IMPORTS,171163,BENNATI CASTELLANO PINOT GRIGIO 750ML,WINE,0.0,0.0,1.0
4,2026,6,20705 IMPORTS,180495,PANAS AGIORGITIKO 750ML,WINE,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...
318841,2017,6,Z WINE GALLERY IMPORTS LLC,345599,DOM DES PERSENADES GROS MANSENG/SAU - 750ML,WINE,0.0,0.0,1.0
318842,2017,6,Z WINE GALLERY IMPORTS LLC,232716,DOM DU VISTRE CUV GLADIATEUR ROSE - 750ML,WINE,0.0,0.0,1.0
318843,2017,6,Z WINE GALLERY IMPORTS LLC,345601,DOM DU VISTRE CUV GLADIATEUR RED - 750ML,WINE,0.0,0.0,1.0
318844,2017,6,Z WINE GALLERY IMPORTS LLC,345592,COMTE DE LANGERON BOURG P/NOIR - 750ML,WINE,0.0,0.0,1.0
318845,2017,6,Z WINE GALLERY IMPORTS LLC,233684,DOM DELIANCE GIVRY PREM CRU LES COMBES - 750ML,WINE,0.0,0.0,1.0

# total_movement

In [3]:
df["total_movement"] = df["retail_transfers"] + df["warehouse_sales"]
df

,year,month,supplier,item_code,item_description,item_type,retail_sales,retail_transfers,warehouse_sales,total_movement
0,2026,6,20705 IMPORTS,180496,PANAS ASSYRTIKO 750ML,WINE,0.0,0.0,2.0,2.0
1,2026,6,20705 IMPORTS,574386,PARDEVALLES ALBARIN BLANCO - 750ML,WINE,0.0,0.0,1.0,1.0
2,2026,6,20705 IMPORTS,171162,PROSECCO 84 - 750ML,WINE,0.0,0.0,4.0,4.0
3,2026,6,20705 IMPORTS,171163,BENNATI CASTELLANO PINOT GRIGIO 750ML,WINE,0.0,0.0,1.0,1.0
4,2026,6,20705 IMPORTS,180495,PANAS AGIORGITIKO 750ML,WINE,0.0,0.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...
318841,2017,6,Z WINE GALLERY IMPORTS LLC,345599,DOM DES PERSENADES GROS MANSENG/SAU - 750ML,WINE,0.0,0.0,1.0,1.0
318842,2017,6,Z WINE GALLERY IMPORTS LLC,232716,DOM DU VISTRE CUV GLADIATEUR ROSE - 750ML,WINE,0.0,0.0,1.0,1.0
318843,2017,6,Z WINE GALLERY IMPORTS LLC,345601,DOM DU VISTRE CUV GLADIATEUR RED - 750ML,WINE,0.0,0.0,1.0,1.0
318844,2017,6,Z WINE GALLERY IMPORTS LLC,345592,COMTE DE LANGERON BOURG P/NOIR - 750ML,WINE,0.0,0.0,1.0,1.0
318845,2017,6,Z WINE GALLERY IMPORTS LLC,233684,DOM DELIANCE GIVRY PREM CRU LES COMBES - 750ML,WINE,0.0,0.0,1.0,1.0

# drop item_description & item_code

because it's high-cardinality text, it will be difficult to encode,we can use item_type for identifier

In [4]:
df = df.drop(columns=["item_description", "item_code"])
df

,year,month,supplier,item_type,retail_sales,retail_transfers,warehouse_sales,total_movement
0,2026,6,20705 IMPORTS,WINE,0.0,0.0,2.0,2.0
1,2026,6,20705 IMPORTS,WINE,0.0,0.0,1.0,1.0
2,2026,6,20705 IMPORTS,WINE,0.0,0.0,4.0,4.0
3,2026,6,20705 IMPORTS,WINE,0.0,0.0,1.0,1.0
4,2026,6,20705 IMPORTS,WINE,0.0,0.0,2.0,2.0
...,...,...,...,...,...,...,...,...
318841,2017,6,Z WINE GALLERY IMPORTS LLC,WINE,0.0,0.0,1.0,1.0
318842,2017,6,Z WINE GALLERY IMPORTS LLC,WINE,0.0,0.0,1.0,1.0
318843,2017,6,Z WINE GALLERY IMPORTS LLC,WINE,0.0,0.0,1.0,1.0
318844,2017,6,Z WINE GALLERY IMPORTS LLC,WINE,0.0,0.0,1.0,1.0
318845,2017,6,Z WINE GALLERY IMPORTS LLC,WINE,0.0,0.0,1.0,1.0

# encoding

In [5]:
df["item_type"].nunique()

8

In [7]:
df["supplier"].nunique()

531

## one-hot encoding item_type

In [8]:
df = pd.get_dummies(df, columns=["item_type"], drop_first=True)

## frequency encoding suppliers

In [9]:
freq = df["supplier"].value_counts()

df["supplier_freq"] = df["supplier"].map(freq)

# save new csv file

In [13]:
data_featured = df.to_csv(r"..\data\processed\feature_engineering_data.csv")